### PR TITLE
Detect mentions

### PR DESCRIPTION
**Pull request by clehner**
- Added detection of bare mentions (that are not in markdown links)
- Added tests

### CODE REVIEW

**Comment by dominictarr** [comment]
hmm, I should refactor the patchdeck composer out,
https://github.com/dominictarr/patchdeck/blob/master/index.js#L270

it uses mentions a bit differently, but is still work in patchwork. names are `[@name](@pubkey)`
I think this is simpler because a single markdown value represents everything the user entered.
I still add the mentions object though, before publishing, so that patchwork understands it.

**Comment by dominictarr** [comment]
merged into 0.1.0

**Comment by clehner** [comment]
> hmm, I should refactor the patchdeck composer out,
> https://github.com/dominictarr/patchdeck/blob/master/index.js#L270

Adding suggest items for the full `[@name](@pubkey)` would be more difficult in e.g. a command-line client

> it uses mentions a bit differently, but is still work in patchwork. names are [@name](@pubkey)
> I think this is simpler because a single markdown value represents everything the user entered.
> I still add the mentions object though, before publishing, so that patchwork understands it.

I assume you mean that because if markdown ref mentions were not in the mentions object then we wouldn't be able to use sbot.links to find them. If links2 parsed markdown to detect mentions, we could use that to get links, but then other info about mentions would be lost, like the message key and data that could otherwise go in a mention object.

I see that transforming the bare `@name` mentions in patchwork involves some [post-processing](https://github.com/ssbc/patchwork/blob/2e1a4c977dffcf9b5cad1c59445efa3b216d3a59/ui/com/markdown.jsx#L12). Maybe that should be moved into ssb-marked, which could take a mentions array option for rendering. Then ssb-mentions could be modified to either take an object of all feed names, or be async and take a function to lookup names to ids

**Comment by dominictarr** [comment]
in the ssb-links plugin i index all the markdown mentions, and index http links too. I think this gives us more flexibility than just the mentions object. I don't like how patchwork handles the `@name` thing. It means you cant edit a name on the fly or just call someone something different one time. But the important thing: it means it works differently to how files are named. a name is a name. what should it matter if you are naming a person or naming a thing?

sbot.links wouldn't find without the mentions object, correct. but the ssb-links plugin is already way more powerful than sbot.links.

**Pull request merged**
